# Generated by Django 3.1.7 on 2021-04-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='case_id',
            field=models.IntegerField(default=0, verbose_name='case id'),
        ),
    ]
